### ISSUE TITLE
local test fail json path

### ISSUE THREAD

**Issue by haggbart** [frdedynamics/student-project-corona#12]
Noticed you added test/ to json paths, did the circleci tests fail without?

Asking because the tests runs fine for me without /test to path, but fails with:

> FileNotFoundError: [Errno 2] No such file or directory: 'test/test_get_sir_data.json'

**Comment by MOJOliciousFTW** [comment]
Circleci runs from root, hence the /test. To re-create locally, run ‘pytest test’ in a terminal while in the project root folder (as is done on circleci).

**Comment by haggbart** [comment]
Makes sense. 'pytest test' works fine locally.

**Comment by MOJOliciousFTW** [comment]
A possible hack is to check if not file exists then use longer path.

**Comment by haggbart** [comment]
alternatively set working dir using os.chdir or use absolute path

> ROOT_DIR = path.dirname(path.abspath(__file__))

and        

> with open(ROOT_DIR + '/test_get_sir_data.json') as json_file:

**Comment by haggbart** [comment]
working dir can easily be changed in the pycharm test configuration though, so not a big deal.

**Comment by MOJOliciousFTW** [comment]
Do it :)

**Comment by MOJOliciousFTW** [comment]
Maybe add ‘closes #12’ to commit message 👍
