### ISSUE TITLE
travis osx

### ISSUE THREAD

**Issue by MOJOliciousFTW** [frdedynamics/student-project-corona#6]
/home/travis/.travis/functions: line 109: ./.travis/install.sh: Permission denied
182The command "./.travis/install.sh" failed and exited with 126 during .

well that`s an issue. how bout them permissions? 

platform darwin -- Python 2.7.17, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
also, osx build seem to use python 2.7, maybe check the config or add install python3 (maybe also alias python, python3).

**Comment by haggbart** [comment]
> platform darwin -- Python 2.7.17, pytest-4.6.9, py-1.8.1, pluggy-0.13.1
also, osx build seem to use python 2.7, maybe check the config or add install python3 (maybe also alias python, python3).

The pip command invoke pip2 or pip3 depending on the context, like installation order. 
Either change the pip pointer to pip3 or use pip3 directly.
